// @ts-check
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { buildTokenOutputs, TokenError } from './pipeline.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
export const tokenSourceDir = join(root, 'src/design-system/tokens/source');
const outputDir = join(root, 'src/design-system/tokens/generated');
const resolverFile = join(tokenSourceDir, 'system-lab.resolver.json');

/** Groups whose direct children become typed keys for component props. */
const keyGroups = [
  { group: 'space', constName: 'spaceTokens', typeName: 'SpaceToken' },
  { group: 'spacing', constName: 'spacingTokens', typeName: 'SpacingToken' },
  { group: 'radius', constName: 'radiusTokens', typeName: 'RadiusToken' },
  { group: 'surface', constName: 'surfaceTokens', typeName: 'SurfaceToken' },
  { group: 'border', constName: 'borderColorTokens', typeName: 'BorderColorToken' },
  { group: 'elevation', constName: 'elevationTokens', typeName: 'ElevationToken' },
  { group: 'size.container', constName: 'containerWidthTokens', typeName: 'ContainerWidthToken' },
  { group: 'size.item', constName: 'itemSizeTokens', typeName: 'ItemSizeToken' },
  { group: 'typography', constName: 'typographyTokens', typeName: 'TypographyToken' },
];

/** @param {string} file */
function readJson(file) {
  try {
    return JSON.parse(readFileSync(file, 'utf8'));
  } catch (error) {
    throw new TokenError(`Could not read ${file}: ${error instanceof Error ? error.message : String(error)}`);
  }
}

/** Builds outputs in memory. Throws TokenError on invalid sources. */
export function generateTokenFiles() {
  const result = buildTokenOutputs(readJson(resolverFile), (ref) => readJson(join(tokenSourceDir, ref)), {
    keyGroups,
    banner: 'Generated by scripts/tokens/build-tokens.mjs from src/design-system/tokens/source. Do not edit.',
  });
  return {
    files: {
      [join(outputDir, 'tokens.css')]: result.css,
      [join(outputDir, 'tokens.ts')]: result.ts,
      [join(outputDir, 'manifest.ts')]: result.manifest,
    },
    tokenCount: result.tokenCount,
    contexts: result.contexts,
  };
}

/** Writes only files whose content changed, so watchers don't loop. */
export function writeTokenFiles() {
  const { files, tokenCount, contexts } = generateTokenFiles();
  mkdirSync(outputDir, { recursive: true });
  const written = [];
  for (const [file, content] of Object.entries(files)) {
    if (existsSync(file) && readFileSync(file, 'utf8') === content) continue;
    writeFileSync(file, content);
    written.push(file);
  }
  return { written, tokenCount, contexts };
}

function checkTokenFiles() {
  const { files } = generateTokenFiles();
  const stale = Object.entries(files)
    .filter(([file, content]) => !existsSync(file) || readFileSync(file, 'utf8') !== content)
    .map(([file]) => file);
  return stale;
}

const isCli = process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href;
if (isCli) {
  try {
    if (process.argv.includes('--check')) {
      const stale = checkTokenFiles();
      if (stale.length) {
        console.error(`Generated token files are out of date. Run "npm run tokens".\n  ${stale.join('\n  ')}`);
        process.exit(1);
      }
      console.log('Token outputs are up to date.');
    } else {
      const { written, tokenCount, contexts } = writeTokenFiles();
      console.log(`Resolved ${tokenCount} tokens for themes: ${contexts.join(', ')}.`);
      console.log(written.length ? `Wrote:\n  ${written.join('\n  ')}` : 'Outputs already up to date.');
    }
  } catch (error) {
    if (error instanceof TokenError) {
      console.error(`Token build failed: ${error.message}`);
      process.exit(1);
    }
    throw error;
  }
}
