import type { AlertOwnProps, CardOwnProps, DialogOwnProps, DisclosureOwnProps, EmptyStateProps, FieldProps, PageHeaderProps, RadioGroupOwnProps, TabsProps } from '@/design-system/composites';
import { propsTable, type ComponentDoc } from '@/features/docs';
import {
  AlertExample,
  CardExample,
  DialogExample,
  DisclosureExample,
  EmptyStateExample,
  FieldExample,
  PageHeaderExample,
  RadioGroupExample,
  TabsExample,
} from '../examples/CompositeExamples';

const space = '"none" | "extraSmall" | "small" | "medium" | "large" | "extraLarge" | "extraExtraLarge"';
const radius = '"none" | "small" | "medium" | "large" | "extraLarge" | "full"';
const surface = '"canvas" | "panel" | "sunken" | "accent"';
const border = '"none" | "subtle" | "default" | "strong"';
const elevation = '"none" | "low" | "medium" | "high"';

export const compositeDocs: ComponentDoc[] = [
  {
    id: 'card',
    purpose:
      'Card groups related content on a bounded surface with optional header and footer regions. Its five styling props each have a component token default, so an unstyled Card already looks right and each prop overrides exactly one decision.',
    whenToUse: ['Collections of comparable items, such as directory entries.', 'Grouping a summary with its actions on a dashboard.'],
    whenNotToUse: ['Page sections that are not separate items: use headings and spacing.', 'A tinted area without regions or elevation: use Box.'],
    props: propsTable<CardOwnProps>({
      as: { type: '"div" | "article" | "section" | "li"', defaultValue: '"div"', description: 'Rendered element. article for self-contained items, li inside lists.' },
      surface: { type: surface, defaultValue: 'card.background (panel)', description: 'Background role.' },
      padding: { type: space, defaultValue: 'card.padding (large)', description: 'Padding around all regions.' },
      radius: { type: radius, defaultValue: 'card.radius (large)', description: 'Corner radius.' },
      border: { type: border, defaultValue: 'card.border (subtle)', description: 'Border color strength at border-width.thin.' },
      elevation: { type: elevation, defaultValue: 'card.elevation (low)', description: 'Shadow depth.' },
      header: { type: 'ReactNode', description: 'Region above the body.' },
      footer: { type: 'ReactNode', description: 'Region below the body, separated by a subtle rule.' },
      children: { type: 'ReactNode', description: 'Body content.' },
    }),
    nativeProps: 'Other props, including aria-labelledby, ref and className, go to the rendered element.',
    precedence: [
      'Each styling prop sets a private property that the CSS reads with the component token as fallback: var(--_background, var(--card-background)). An explicit prop always wins; an unset prop always uses the token.',
      'Changing a card.* token restyles every Card that has not opted out, which is how a product retunes cards in one place.',
      'border="none" keeps the border box so cards with and without borders align, and forced-colors mode still shows an edge.',
      'All combinations are valid. elevation="none" with border="none" on surface="canvas" produces an invisible card, which is allowed but rarely useful.',
    ],
    propTokens: [
      { prop: 'surface unset', property: 'background-color', token: 'card.background' },
      { prop: 'surface="sunken"', property: 'background-color', token: 'surface.sunken' },
      { prop: 'padding unset', property: 'padding', token: 'card.padding' },
      { prop: 'elevation unset', property: 'box-shadow', token: 'card.elevation' },
      { prop: 'elevation="high"', property: 'box-shadow', token: 'elevation.high' },
    ],
    composition: [
      'The card is visual only: put a Link in the title and Buttons in the footer rather than making the whole card a link.',
      'EntryCard in the domain layer composes Card, Badge, Link and Button for catalog entries.',
    ],
    states: ['None of its own. Interactive children keep their own states.'],
    accessibility: ['Use as="article" with a heading for self-contained items so they are listed as articles.', 'Avoid nested interactive regions: one action per target.'],
    responsive: ['Card shrinks with its container. Content inside can adapt with container queries, as EntryCard does at 28rem.'],
    mistakes: ['Wrapping the card in an anchor, which makes its buttons invalid nested interactive content.', 'Overriding padding with className, which skips the scale.'],
    tradeoffs: ['Regions are fixed (header, body, footer). Media that bleeds to the edge needs padding="none" and its own inner padding.'],
    sourcePaths: ['src/design-system/composites/Card/Card.tsx', 'src/design-system/composites/Card/Card.module.css'],
    Example: CardExample,
  },
  {
    id: 'dialog',
    purpose:
      'Dialog is a modal built on the native dialog element. showModal() provides the focus trap, the inert background, top-layer rendering and Escape; Dialog adds controlled state, labelling, initial focus, focus restoration and the same token-backed styling props as Card.',
    whenToUse: ['Confirming a destructive or irreversible action.', 'A short, focused task that must finish before returning to the page.'],
    whenNotToUse: ['Information people need while they keep working: use an inline Alert.', 'Long forms: use a page.'],
    props: propsTable<DialogOwnProps>({
      open: { type: 'boolean', required: true, description: 'Whether the dialog is shown. Always controlled.' },
      onClose: { type: '() => void', required: true, description: 'Called for Escape, the close button, native close and, with dismissOnBackdrop, a backdrop click. Set open to false.' },
      title: { type: 'ReactNode', required: true, description: 'Visible title and accessible name (aria-labelledby).' },
      description: { type: 'ReactNode', description: 'Accessible description (aria-describedby).' },
      size: { type: '"small" | "medium" | "large"', defaultValue: '"medium"', description: 'Maximum width from dialog.width.*; always fits the viewport.' },
      surface: { type: surface, defaultValue: 'dialog.background (panel)', description: 'Background role.' },
      padding: { type: space, defaultValue: 'dialog.padding (large)', description: 'Padding.' },
      radius: { type: radius, defaultValue: 'dialog.radius (extraLarge)', description: 'Corner radius.' },
      border: { type: border, defaultValue: 'dialog.border (subtle)', description: 'Border color strength.' },
      elevation: { type: elevation, defaultValue: 'dialog.elevation (high)', description: 'Shadow depth.' },
      header: { type: 'ReactNode', description: 'Extra header content beside the title, such as a badge.' },
      footer: { type: 'ReactNode', description: 'Actions row, aligned to the end.' },
      initialFocus: { type: 'RefObject<HTMLElement | null>', description: 'Element to focus on open. Defaults to the first focusable element (the close button).' },
      closeLabel: { type: 'string', defaultValue: '"Close"', description: 'Accessible name of the close button.' },
      dismissOnBackdrop: {
        type: 'boolean',
        defaultValue: 'false',
        description: 'Call onClose when a click starts and ends on the backdrop. Independent of Escape and the close button, which always work.',
      },
      children: { type: 'ReactNode', description: 'Body content.' },
    }),
    nativeProps: 'Dialog does not spread native props: its element is managed by showModal() and a stray open attribute would make it non-modal.',
    precedence: [
      'Styling precedence matches Card: explicit props win, unset props use dialog.* tokens.',
      'size caps the width; the viewport always wins (min(size, 100% − 2 × spacing.medium)).',
      'initialFocus wins over the default first-focusable rule. For confirmations, pass the Cancel button.',
      'Escape (cancel) is turned into onClose so React state stays the single source of truth.',
    ],
    propTokens: [
      { prop: 'size="medium"', property: 'inline-size', token: 'dialog.width.medium' },
      { prop: 'surface unset', property: 'background-color', token: 'dialog.background' },
      { prop: 'elevation unset', property: 'box-shadow', token: 'dialog.elevation' },
      { prop: '(backdrop)', property: '::backdrop background', token: 'dialog.backdrop' },
    ],
    composition: ['Footer actions are Buttons: Cancel first in source, the confirming action last and primary or danger.', 'Show operation errors inside the dialog with an Alert role="alert" and keep the dialog open.'],
    states: ['Closed, open, and whatever the consumer renders: pending (loading button) and error (Alert) in the examples.'],
    accessibility: [
      'role dialog and aria-modal come from showModal(); the background is inert.',
      'Focus moves in on open and returns to the opener on close, including after Strict Mode remounts.',
      'Tab and Shift+Tab wrap between the first and last controls; the native modal alone would let focus leave for the browser UI. Escape closes.',
      'The close button has an accessible name; its icon is hidden.',
    ],
    responsive: ['Width and height are capped by the viewport; content scrolls inside the dialog when it is taller than the screen.', 'The entry animation runs only when reduced motion is not requested.'],
    mistakes: ['Closing the dialog when the action fails, which hides the error.', 'Opening a dialog on page load.', 'Using a dialog for a message that does not need a decision.'],
    tradeoffs: [
      'Backdrop clicks close the dialog only with dismissOnBackdrop. It is off by default so a stray click cannot discard input; turn it on for dialogs with nothing to lose.',
      'Relies on ::backdrop inheriting custom properties (all current browsers).',
    ],
    sourcePaths: ['src/design-system/composites/Dialog/Dialog.tsx', 'src/design-system/composites/Dialog/Dialog.module.css'],
    Example: DialogExample,
  },
  {
    id: 'alert',
    purpose: 'Alert reports the state of the page or an operation. The tone sets surface, border, icon and title color together; the title states the meaning in words.',
    whenToUse: ['Operation results and errors with a recovery action.', 'Page-level notices.'],
    whenNotToUse: ['Short status labels: use Badge.', 'Messages that need a decision: use Dialog.'],
    props: propsTable<AlertOwnProps>({
      tone: { type: '"info" | "success" | "warning" | "danger"', defaultValue: '"info"', description: 'Status role.' },
      title: { type: 'ReactNode', required: true, description: 'Short summary.' },
      children: { type: 'ReactNode', description: 'Detail and guidance.' },
      actions: { type: 'ReactNode', description: 'Recovery or follow-up actions.' },
    }),
    nativeProps: 'Other props go to the wrapper div, including role.',
    precedence: ['The component never adds a live role. Pass role="alert" for urgent messages that appear after an action and role="status" for polite ones.'],
    propTokens: [
      { prop: 'tone="danger"', property: 'background-color', token: 'tone.danger.surface' },
      { prop: 'tone="danger"', property: 'border-color', token: 'tone.danger.border' },
      { prop: 'tone="danger"', property: 'color (title)', token: 'tone.danger.text' },
    ],
    composition: ['Error states in the pattern demos use Alert with a Retry Button in actions.'],
    states: ['Static.'],
    accessibility: ['Icon is decorative; the title carries the meaning.', 'A live role on an alert that is present at page load is announced at an unexpected time; add it only for dynamic messages.'],
    responsive: ['The icon column stays fixed; text wraps.'],
    mistakes: ['role="alert" on every alert.', 'An error alert without a way to recover.'],
    tradeoffs: ['Neutral and brand tones are not offered, because an alert always communicates status.'],
    sourcePaths: ['src/design-system/composites/Alert/Alert.tsx', 'src/design-system/composites/Alert/Alert.module.css'],
    Example: AlertExample,
  },
  {
    id: 'tabs',
    purpose: 'Tabs switch between related panels using the ARIA tabs pattern with automatic activation.',
    whenToUse: ['Alternative views of one thing, such as usage, tokens and changes of an entry.'],
    whenNotToUse: ['Sequential steps.', 'Navigation between pages: use links.'],
    props: propsTable<TabsProps>({
      label: { type: 'string', required: true, description: 'Accessible name of the tab list.' },
      items: { type: 'readonly TabItem[]', required: true, description: '{ id, label, content } per tab.' },
      defaultSelectedId: { type: 'string', defaultValue: 'first item', description: 'Initially selected tab.' },
      onSelectedChange: { type: '(id: string) => void', description: 'Called after selection changes.' },
    }),
    nativeProps: 'No native props are spread.',
    precedence: ['Uncontrolled by design: the selected tab is UI state, not application data.'],
    propTokens: [{ prop: 'selected tab', property: 'background-color (the indicator)', token: 'signal.current' }],
    composition: ['The resource detail pattern uses Tabs for overview, tokens and history.'],
    states: ['Selected, unselected, hover, focus-visible.'],
    accessibility: ['One tab stop for the list; arrow keys (reversed in right-to-left), Home and End move and select.', 'Panels are focusable so keyboard users can reach content without interactive elements.', 'Hidden panels stay mounted to preserve their state.'],
    responsive: ['The tab list scrolls horizontally instead of wrapping into multiple rows.'],
    mistakes: ['Putting critical content in a non-default tab.'],
    tradeoffs: ['Automatic activation suits light panels; heavy panels would need manual activation.'],
    sourcePaths: ['src/design-system/composites/Tabs/Tabs.tsx', 'src/design-system/composites/Tabs/Tabs.module.css'],
    Example: TabsExample,
  },
  {
    id: 'disclosure',
    purpose:
      'Disclosure shows and hides secondary content behind a short summary. It is the native details and summary elements with the system’s target size, marker, focus ring and surfaces, plus an optional lazy mode for content that is expensive to render.',
    whenToUse: ['Detail most people skip: source files, token chains, rendered markup, FAQs.', 'Long reference lists where each item expands to more detail.'],
    whenNotToUse: ['Switching between views of the same thing: use Tabs.', 'Content everyone needs, such as an error or a required instruction.', 'Navigation menus.'],
    props: propsTable<DisclosureOwnProps>({
      summary: { type: 'ReactNode', required: true, description: 'Always-visible label; the accessible name of the toggle.' },
      children: { type: 'ReactNode', description: 'Content shown while open.' },
      appearance: { type: '"bordered" | "flush"', defaultValue: '"bordered"', description: 'A standalone panel, or a row inside another surface.' },
      defaultOpen: { type: 'boolean', defaultValue: 'false', description: 'Open on first render; uncontrolled afterwards.' },
      lazy: { type: 'boolean', defaultValue: 'false', description: 'Render the content only while open.' },
      onOpenChange: { type: '(open: boolean) => void', description: 'Called after the person toggles it.' },
    }),
    nativeProps: 'Other props, including id, name (an exclusive group), ref and className, go to the details element. open and onToggle are owned by the component.',
    precedence: [
      'defaultOpen sets the initial state only; the native element owns it afterwards, so find-in-page can open it too.',
      'lazy only affects rendering: closed content is never in the DOM, so it is also excluded from find-in-page.',
    ],
    propTokens: [
      { prop: 'summary row', property: 'min-block-size', token: 'control.height.small' },
      { prop: 'appearance="bordered"', property: 'border-color', token: 'border.subtle' },
      { prop: 'appearance="bordered"', property: 'background-color', token: 'surface.panel' },
    ],
    composition: [
      'Component pages use bordered disclosures for prop → token traces and source files, and flush ones for the Source and Rendered HTML rows of every live example.',
      'Put a ScrollRegion inside for code, so wide lines scroll within the panel.',
    ],
    states: ['Closed, open, hover, focus-visible.'],
    accessibility: [
      'Native summary: announced with its expanded state, toggled with Enter or Space, one tab stop.',
      'The summary row is at least control.height.small (28px compact, 32px comfortable), above the 24px target minimum.',
      'The chevron is decorative and hidden from assistive technology; it mirrors in right-to-left.',
      'The focus ring is drawn inside the row, so it is never clipped by a rounded parent.',
    ],
    responsive: ['The summary wraps instead of truncating, and the row grows with it.'],
    mistakes: ['Putting interactive controls inside the summary, which nests them in the toggle.', 'Hiding information people need to complete the task.'],
    tradeoffs: ['Uncontrolled by design. A parent that must open it programmatically should render content directly instead.'],
    sourcePaths: ['src/design-system/composites/Disclosure/Disclosure.tsx', 'src/design-system/composites/Disclosure/Disclosure.module.css'],
    Example: DisclosureExample,
  },
  {
    id: 'field',
    purpose: 'Field connects one control to its label, description and error. The render-function child makes the wiring visible at the call site.',
    whenToUse: ['Every Input and Select.'],
    whenNotToUse: ['Checkbox and Switch, which label themselves.'],
    props: propsTable<FieldProps>({
      label: { type: 'ReactNode', required: true, description: 'Visible label.' },
      description: { type: 'ReactNode', description: 'Hint announced with the control.' },
      error: { type: 'ReactNode', description: 'Error message; marks the control invalid.' },
      required: { type: 'boolean', defaultValue: 'false', description: 'Marks the control required and shows “(required)”.' },
      id: { type: 'string', defaultValue: 'generated', description: 'Control id.' },
      className: { type: 'string', description: 'Class for the wrapper.' },
      children: { type: '(control: FieldControlProps) => ReactNode', required: true, description: 'Receives id, aria-describedby, aria-invalid and required.' },
    }),
    nativeProps: 'No native props are spread; everything goes through the render function.',
    precedence: ['error adds aria-invalid and appends the error id after the description id in aria-describedby.'],
    propTokens: [{ prop: 'error', property: 'color', token: 'tone.danger.text' }],
    composition: ['The form validation pattern adds an error summary that links to each Field.'],
    states: ['Default, required, invalid.'],
    accessibility: ['Label, description and error are programmatically associated.', 'The error has an icon and text, never color alone.'],
    responsive: ['Fills its container.'],
    mistakes: ['Showing errors on every keystroke before submit.'],
    tradeoffs: ['A render function is slightly more verbose than cloneElement but explicit and type-safe.'],
    sourcePaths: ['src/design-system/composites/Field/Field.tsx', 'src/design-system/composites/Field/Field.module.css'],
    Example: FieldExample,
  },
  {
    id: 'page-header',
    purpose: 'PageHeader introduces a page with its only h1, plus optional eyebrow, description, metadata and actions.',
    whenToUse: ['The top of every page.'],
    whenNotToUse: ['Section headings inside a page.'],
    props: propsTable<PageHeaderProps>({
      title: { type: 'ReactNode', required: true, description: 'The h1.' },
      eyebrow: { type: 'ReactNode', description: 'Short context above the title, such as the section name.' },
      description: { type: 'ReactNode', description: 'Lead text.' },
      meta: { type: 'ReactNode', description: 'Metadata row.' },
      actions: { type: 'ReactNode', description: 'Page actions.' },
      titleSize: { type: '"display" | "extraLarge"', defaultValue: '"extraLarge"', description: 'Visual size of the h1.' },
      titleRef: { type: 'Ref<HTMLHeadingElement>', description: 'Receives the focusable h1 for focus after navigation.' },
    }),
    nativeProps: 'No native props are spread.',
    precedence: [],
    propTokens: [{ prop: 'titleSize="display"', property: 'font-size', token: 'font.size.4xl', readBy: 'heading' }],
    composition: ['Every page in this site renders one PageHeader.'],
    states: ['The h1 receives focus after client-side navigation.'],
    accessibility: ['tabIndex={-1} lets the app move focus to the h1 without adding it to the tab order.'],
    responsive: ['Actions wrap below the text in narrow containers.'],
    mistakes: ['Putting two PageHeaders on one page, which creates two h1 elements.'],
    tradeoffs: ['Only two title sizes, to keep page tops consistent.'],
    sourcePaths: ['src/design-system/composites/PageHeader/PageHeader.tsx', 'src/design-system/composites/PageHeader/PageHeader.module.css', 'src/app/shell/usePageTitle.ts'],
    Example: PageHeaderExample,
  },
  {
    id: 'empty-state',
    purpose: 'EmptyState explains why a region has no content and offers a next step.',
    whenToUse: ['Lists with no data yet.', 'Filtered views that match nothing (with a Clear filters action).'],
    whenNotToUse: ['Errors: use Alert with a retry.'],
    props: propsTable<EmptyStateProps>({
      title: { type: 'ReactNode', required: true, description: 'What is missing.' },
      description: { type: 'ReactNode', description: 'Why, and what to do.' },
      action: { type: 'ReactNode', description: 'The next step.' },
      headingLevel: { type: '2 | 3 | 4', defaultValue: '2', description: 'Heading level that fits the outline.' },
    }),
    nativeProps: 'No native props are spread.',
    precedence: [],
    propTokens: [{ prop: '(always)', property: 'border-radius', token: 'card.radius' }],
    composition: ['The directory pattern distinguishes Empty (no data) from No results (filters too narrow) with two different EmptyStates.'],
    states: ['Static.'],
    accessibility: ['Uses a real heading so it appears in the outline.'],
    responsive: ['Text wraps; the action keeps its natural width.'],
    mistakes: ['The same message for “nothing exists” and “nothing matches”.'],
    tradeoffs: ['No illustration slot: words carry the message.'],
    sourcePaths: ['src/design-system/composites/EmptyState/EmptyState.tsx', 'src/design-system/composites/EmptyState/EmptyState.module.css'],
    Example: EmptyStateExample,
  },
  {
    id: 'radio-group',
    purpose:
      'RadioGroup asks for one choice from a short set, on native radio buttons inside a fieldset. The cards appearance gives each option room for a description and a large target.',
    whenToUse: ['Two to seven mutually exclusive options that should all be visible.', 'Options that need a sentence of explanation each (cards).'],
    whenNotToUse: ['Long lists or options the reader can type: use Select.', 'An immediate on/off setting: use Switch.', 'Several independent choices: use Checkboxes.'],
    props: propsTable<RadioGroupOwnProps>({
      legend: { type: 'ReactNode', required: true, description: 'Visible group label and the fieldset’s accessible name.' },
      description: { type: 'ReactNode', description: 'Hint announced when the group is entered.' },
      options: { type: 'RadioOption[]', required: true, description: 'value, label and optional description and disabled for each option.' },
      value: { type: 'string', description: 'Controlled selection.' },
      defaultValue: { type: 'string', description: 'Initial selection for an uncontrolled group.' },
      onChange: { type: '(value) => void', description: 'Called with the newly selected value.' },
      name: { type: 'string', defaultValue: 'generated', description: 'Form field name. Set it when the group submits with a form.' },
      appearance: { type: '"list" | "cards"', defaultValue: '"list"', description: 'Plain radios or selectable cards.' },
      error: { type: 'ReactNode', description: 'Error message, announced with the group and shown with an icon.' },
      required: { type: 'boolean', defaultValue: 'false', description: 'Marks every radio required and shows “(required)”.' },
      disabled: { type: 'boolean', defaultValue: 'false', description: 'Disables the whole group through the fieldset.' },
    }),
    nativeProps: 'No native props are spread; the fieldset and inputs are wired from the props above.',
    precedence: ['value wins over defaultValue; pass value and onChange together for a controlled group.', 'A disabled option stays visible so the set of choices does not change shape.'],
    propTokens: [
      { prop: 'appearance="cards"', property: 'border-radius', token: 'radio-group.card-radius' },
      { prop: 'appearance="cards" (checked)', property: 'border-color', token: 'radio-group.card-border-checked' },
      { prop: '(always)', property: 'accent-color', token: 'action.primary.background' },
    ],
    composition: ['Use the cards appearance in guided flows where each option needs a sentence of explanation.', 'Use the list appearance inside dialogs and dense forms, such as choosing a reason.'],
    states: ['Unselected, selected, focus-visible (on the card in the cards appearance), disabled option, disabled group, invalid.'],
    accessibility: [
      'Native radios in a fieldset with the radiogroup role: Tab enters the group once, arrow keys move and select, and the legend names the group.',
      'The group description and error are referenced from the fieldset, which is marked invalid when there is an error; each option’s description is referenced from its radio.',
      'In the cards appearance the whole card is the label, so the target is at least the card’s size.',
      'Forced-colors mode draws the checked card with the system Highlight color.',
    ],
    responsive: ['Cards fill as many columns as fit at a 14rem minimum and stack in narrow containers; the list appearance is always one column.'],
    mistakes: ['Using cards for one-word options, which wastes space: use the list appearance.', 'Leaving no option selected and no error when a choice is required.'],
    tradeoffs: ['Cards are fixed to a grid of equal columns; options with very different lengths look uneven.'],
    sourcePaths: ['src/design-system/composites/RadioGroup/RadioGroup.tsx', 'src/design-system/composites/RadioGroup/RadioGroup.module.css'],
    Example: RadioGroupExample,
  },
];
