import type {
  BadgeOwnProps,
  ButtonOwnProps,
  CheckboxOwnProps,
  HeadingOwnProps,
  IconOwnProps,
  LinkOwnProps,
  ProgressOwnProps,
  SkeletonOwnProps,
  SwitchOwnProps,
  TextOwnProps,
} from '@/design-system/primitives';
import { propsTable, type ComponentDoc } from '@/features/docs';
import {
  BadgeExample,
  ButtonExample,
  CheckboxExample,
  HeadingExample,
  IconExample,
  InputExample,
  LinkExample,
  ProgressExample,
  SelectExample,
  SkeletonExample,
  SwitchExample,
  TextExample,
  VisuallyHiddenExample,
} from '../examples/PrimitiveExamples';

const radius = '"none" | "small" | "medium" | "large" | "extraLarge" | "full"';
const tone = '"neutral" | "brand" | "success" | "warning" | "danger" | "info"';

export const primitiveDocs: ComponentDoc[] = [
  {
    id: 'text',
    purpose: 'Text renders running copy in one of five typography styles. The element is chosen for meaning and the variant for appearance, so a caption can be a span and a lead paragraph can be a p.',
    whenToUse: ['Paragraphs, labels, captions and metadata.', 'Status and error messages that need a tone.'],
    whenNotToUse: ['Headings: use Heading so the outline is correct.', 'Long authored documentation: plain HTML inside Prose is easier to write.'],
    props: propsTable<TextOwnProps>({
      as: { type: '"p" | "span" | "div" | "small" | "strong" | "em" | "figcaption" | "dt" | "dd" | "li"', defaultValue: '"p"', description: 'Rendered element.' },
      variant: { type: '"body" | "bodySmall" | "lead" | "label" | "caption"', defaultValue: '"body"', description: 'Typography composite token.' },
      tone: { type: '"default" | "muted" | "brand" | "success" | "warning" | "danger" | "info"', defaultValue: '"default"', description: 'Text color role.' },
      align: { type: '"start" | "center" | "end"', defaultValue: '"start"', description: 'Logical alignment.' },
    }),
    nativeProps: 'Other props, including id, role and aria-*, go to the rendered element.',
    precedence: ['Paragraph text (as="p") is capped at layout.measure for readability; other elements are not.', 'tone only sets color; it never changes weight or size.'],
    propTokens: [
      { prop: 'variant="lead"', property: 'font-size', token: 'typography.lead' },
      { prop: 'tone="muted"', property: 'color', token: 'text.muted' },
      { prop: 'tone="danger"', property: 'color', token: 'tone.danger.text' },
    ],
    composition: ['Inside Stack for paragraphs; inside Inline for metadata rows.'],
    states: ['None.'],
    accessibility: ['Every tone meets 4.5:1 on every surface in both themes (checked in contrast.test.ts).', 'caption is uppercase via CSS, so screen readers read the original casing.'],
    responsive: ['Sizes are rem-based and follow the reader’s font-size setting.'],
    mistakes: ['Using tone="danger" as the only error signal: include words such as “Error:” or an icon.', 'Choosing as="span" inside a p for a second paragraph.'],
    tradeoffs: ['No arbitrary font sizes: new needs become new typography tokens.'],
    sourcePaths: ['src/design-system/primitives/Text/Text.tsx', 'src/design-system/primitives/Text/Text.module.css'],
    Example: TextExample,
  },
  {
    id: 'heading',
    purpose: 'Heading separates outline level from visual size. The level is required and comes from the page structure; size defaults from the level but can be changed without breaking the outline.',
    whenToUse: ['Every section heading.', 'Card and dialog titles.'],
    whenNotToUse: ['Bold text that does not start a section: use Text with variant="label".'],
    props: propsTable<HeadingOwnProps>({
      level: { type: '1 | 2 | 3 | 4 | 5 | 6', required: true, description: 'Outline level.' },
      size: { type: '"display" | "extraLarge" | "large" | "medium" | "small"', defaultValue: 'from level', description: 'Typography style. 1 → extraLarge, 2 → large, 3 → medium, 4–6 → small.' },
      tone: { type: '"default" | "muted" | "brand"', defaultValue: '"default"', description: 'Text color role.' },
      align: { type: '"start" | "center" | "end"', defaultValue: '"start"', description: 'Logical alignment.' },
    }),
    nativeProps: 'Other props go to the h1–h6 element, including id (for aria-labelledby) and tabIndex (for focus after navigation).',
    precedence: ['An explicit size always wins over the level default.', 'display is fluid between font.size.3xl and font.size.4xl; the others are fixed tokens.'],
    propTokens: [
      { prop: 'size="large"', property: 'font-size', token: 'typography.heading-2' },
      { prop: 'tone="muted"', property: 'color', token: 'text.muted' },
    ],
    composition: ['PageHeader renders the page’s h1; sections use level 2 and below.'],
    states: ['Focusable with tabIndex={-1} after route changes; the focus outline shows only for keyboard focus.'],
    accessibility: ['Do not skip levels to get a smaller size: use size instead.'],
    responsive: ['display scales with the viewport but never below font.size.3xl, so zoom still enlarges it.'],
    mistakes: ['Picking level={4} because it looks right.', 'Two h1 elements on one page.'],
    tradeoffs: ['Five sizes for six levels: levels 4–6 share a style because deeper outlines are rare in this product.'],
    sourcePaths: ['src/design-system/primitives/Heading/Heading.tsx', 'src/design-system/primitives/Heading/Heading.module.css'],
    Example: HeadingExample,
  },
  {
    id: 'button',
    purpose:
      'Button is a native <button> with a deliberate set of visual choices: appearance sets the colors, size sets height, padding and type size, border sets the border width, and radius sets the corners. Colors resolve through Button’s component tokens to semantic action roles, which each theme and product maps to a palette color. Geometry takes other paths: size uses Button’s size tokens, whose height and padding follow density; border reads the fixed border-width scale; and an unset radius uses button.radius, which follows the product, while an explicit radius reads the radius scale directly.',
    whenToUse: ['Actions that change something on this page: save, delete, open a dialog, retry.', 'Form submission (type="submit").'],
    whenNotToUse: ['Navigation to another page: use Link, even if it should look prominent.', 'Toggling a persistent setting: use Switch.'],
    props: propsTable<ButtonOwnProps>({
      appearance: { type: '"primary" | "secondary" | "ghost" | "danger"', defaultValue: '"secondary"', description: 'Background treatment and emphasis.' },
      size: { type: '"small" | "medium" | "large"', defaultValue: '"medium"', description: 'Height, inline padding and font size from button.* tokens.' },
      border: { type: '"none" | "thin" | "thick"', defaultValue: '"thin"', description: 'Border width. Color always comes from the appearance.' },
      radius: { type: radius, defaultValue: 'button.radius token', description: 'Corner radius. Unset uses the button.radius component token, which aliases control.radius.' },
      fullWidth: { type: 'boolean', defaultValue: 'false', description: 'Fill the container’s inline size.' },
      loading: { type: 'boolean', defaultValue: 'false', description: 'Show a progress indicator, set aria-disabled and ignore clicks while keeping focus.' },
      iconStart: { type: 'ReactNode', description: 'Decorative icon before the label; replaced by the spinner while loading.' },
      iconEnd: { type: 'ReactNode', description: 'Decorative icon after the label.' },
    }),
    nativeProps: 'All native button attributes pass through. type defaults to "button" so a Button inside a form never submits by accident; pass type="submit" explicitly.',
    precedence: [
      'disabled overrides every appearance with the button.disabled.* tokens; it is declared last in the CSS for that reason.',
      'loading keeps the appearance (so the button does not flash grey) and replaces iconStart with the spinner.',
      'border="none" removes the width only; in forced-colors mode a 1px system border is always drawn so the button stays visible.',
      'An explicit radius wins over the button.radius token through a private --_radius property.',
      'Valid with any combination: there are no props that conflict.',
    ],
    propTokens: [
      { prop: 'appearance="primary"', property: 'background-color', token: 'button.primary.background' },
      { prop: 'appearance="primary" (hover)', property: 'background-color', token: 'button.primary.background-hover' },
      { prop: 'appearance="danger"', property: 'color', token: 'button.danger.foreground' },
      { prop: 'size="large"', property: 'min-block-size', token: 'button.height.large' },
      { prop: 'border="thick"', property: 'border-width', token: 'border-width.thick' },
      { prop: 'radius unset', property: 'border-radius', token: 'button.radius' },
      { prop: 'disabled', property: 'background-color', token: 'button.disabled.background' },
    ],
    composition: ['Group buttons with Inline; put the primary action last in a dialog footer and first in a page toolbar.', 'Pass <Icon /> to iconStart or iconEnd; the wrapper is aria-hidden.'],
    states: ['Default, hover, active (pressed), focus-visible (global focus ring), disabled (native) and loading (aria-disabled).'],
    accessibility: [
      'The accessible name is the label. Icon-only buttons need aria-label.',
      'loading uses aria-disabled instead of disabled so focus is not lost mid-action; announce the outcome with a status message.',
      'At comfortable density, small, medium and large are 32, 44 and 52px tall at the default text size; compact density makes them 28, 36 and 44px. Every height is above the 24px minimum in WCAG 2.2 target size (2.5.8).',
      'Foreground on background, hover and active backgrounds meets 4.5:1 in both themes.',
    ],
    responsive: ['Labels wrap inside narrow containers instead of overflowing; fullWidth is the usual choice in narrow dialogs and cards.'],
    mistakes: ['Two primary buttons side by side.', 'Using Button with onClick to navigate.', 'Setting disabled while saving, which drops keyboard focus to the page.'],
    tradeoffs: ['Four appearances only. A new treatment needs component tokens for all five states, which keeps every appearance complete.'],
    sourcePaths: ['src/design-system/primitives/Button/Button.tsx', 'src/design-system/primitives/Button/Button.module.css', 'src/design-system/tokens/source/component.tokens.json'],
    Example: ButtonExample,
  },
  {
    id: 'badge',
    purpose:
      'Badge labels status or category. A tone provides five roles (text, surface, border, solid, on-solid) and the appearance decides which of them become the background, foreground and border.',
    whenToUse: ['Maturity, status and category labels.', 'Counts and short tags next to titles.'],
    whenNotToUse: ['Anything clickable: Badge is not interactive.', 'Long messages: use Alert.'],
    props: propsTable<BadgeOwnProps>({
      tone: { type: tone, defaultValue: '"neutral"', description: 'Color role from tone.* tokens.' },
      appearance: { type: '"filled" | "subtle" | "outlined"', defaultValue: '"subtle"', description: 'filled: solid/on-solid. subtle: surface/text. outlined: transparent/text/border.' },
      size: { type: '"small" | "medium" | "large"', defaultValue: '"medium"', description: 'Height, padding and font size from badge.* tokens.' },
      radius: { type: radius, defaultValue: 'badge.radius token (full)', description: 'Corner radius.' },
      icon: { type: 'ReactNode', description: 'Decorative icon before the label.' },
    }),
    nativeProps: 'Other props go to the span.',
    precedence: ['tone and appearance are independent: any of the 18 combinations is valid and contrast-checked.', 'An explicit radius wins over badge.radius.'],
    propTokens: [
      { prop: 'tone="success" appearance="subtle"', property: 'background-color', token: 'tone.success.surface' },
      { prop: 'tone="success" appearance="subtle"', property: 'color', token: 'tone.success.text' },
      { prop: 'tone="danger" appearance="filled"', property: 'background-color', token: 'tone.danger.solid' },
      { prop: 'tone="info" appearance="outlined"', property: 'border-color', token: 'tone.info.border' },
      { prop: 'size="small"', property: 'min-block-size', token: 'badge.height.small' },
    ],
    composition: ['MaturityBadge in the domain layer maps a maturity to a tone, so pages never choose status colors by hand.'],
    states: ['None.'],
    accessibility: ['The label states the meaning; tone only repeats it.', 'Text on surface and on-solid on solid meet 4.5:1 in both themes.'],
    responsive: ['Badges do not wrap internally (white-space: nowrap); put them in an Inline so the group wraps.'],
    mistakes: ['A green badge that says only “3”.', 'Using filled for every badge, which removes hierarchy.'],
    tradeoffs: ['Six tones cover status and brand; product categories should map onto them rather than add colors.'],
    sourcePaths: ['src/design-system/primitives/Badge/Badge.tsx', 'src/design-system/primitives/Badge/Badge.module.css'],
    Example: BadgeExample,
  },
  {
    id: 'icon',
    purpose: 'Icon draws one of a small fixed set of stroke icons in currentColor. It is decorative unless given a label.',
    whenToUse: ['Inside Button, Badge and Alert slots.', 'Reinforcing a label, never replacing it, except in icon-only buttons with aria-label.'],
    whenNotToUse: ['Illustrations: use an image with alt text.'],
    props: propsTable<IconOwnProps>({
      name: { type: 'IconName', required: true, description: 'One of the exported iconNames.' },
      size: { type: '"small" | "medium" | "large"', defaultValue: '1em', description: 'Size from size.icon.*; unset matches the surrounding text.' },
      label: { type: 'string', description: 'Accessible name. Without it the icon is aria-hidden.' },
    }),
    nativeProps: 'Other SVG props pass through; children are not accepted.',
    precedence: ['label switches the role from hidden to img; there is no other way to expose an icon.'],
    propTokens: [{ prop: 'size="large"', property: 'inline-size', token: 'size.icon.lg' }],
    composition: ['Color comes from the parent, so an Icon inside a danger Badge is already the right color.'],
    states: ['None.'],
    accessibility: ['Decorative icons are hidden; meaningful ones need a label.', 'focusable="false" prevents legacy browsers from adding a tab stop.'],
    responsive: ['Scales with text when size is unset.'],
    mistakes: ['Giving an icon a label inside a button that already has a text label, which reads the name twice.'],
    tradeoffs: ['A fixed set keeps the visual language consistent; new icons are added to the component, not passed in as arbitrary SVG.'],
    sourcePaths: ['src/design-system/primitives/Icon/Icon.tsx', 'src/design-system/primitives/Icon/Icon.module.css'],
    Example: IconExample,
  },
  {
    id: 'link',
    purpose: 'Link renders a real anchor. App-relative paths are routed client-side through LinkProvider, so the design system needs no router dependency.',
    whenToUse: ['Navigation to another page or location.'],
    whenNotToUse: ['Actions: use Button.'],
    props: propsTable<LinkOwnProps>({
      href: { type: 'string', required: true, description: 'Destination. Paths starting with / use the provider’s navigate.' },
      variant: { type: '"inline" | "standalone"', defaultValue: '"inline"', description: 'inline is always underlined; standalone underlines on hover.' },
    }),
    nativeProps: 'All anchor attributes pass through. Modified clicks, target, download and external URLs fall back to normal browser behavior.',
    precedence: ['An onClick that calls preventDefault stops client-side routing.'],
    propTokens: [{ prop: 'variant="inline"', property: 'color', token: 'text.link' }],
    composition: ['The app wraps everything in LinkProvider with React Router’s navigate.'],
    states: ['Default, hover, focus-visible, visited (same color by design).'],
    accessibility: ['Link text must describe the destination.', 'Inline links are underlined because color alone cannot identify them.'],
    responsive: ['Long URLs wrap inside their container.'],
    mistakes: ['“Click here” link text.'],
    tradeoffs: ['Visited links are not styled differently, because most links here are navigation within a reference site.'],
    sourcePaths: ['src/design-system/primitives/Link/Link.tsx', 'src/design-system/primitives/Link/Link.module.css'],
    Example: LinkExample,
  },
  {
    id: 'input',
    purpose: 'Input is a styled native text input. It adds no props: everything is native, and invalid styling follows aria-invalid, which Field sets.',
    whenToUse: ['Single-line text, email, search, URL and password entry.'],
    whenNotToUse: ['Choosing from a short known list: use Select.', 'A standalone input without a visible label.'],
    props: [],
    nativeProps: 'Every input attribute passes through. type defaults to "text". Use it controlled (value + onChange) or uncontrolled (defaultValue), not both.',
    precedence: ['aria-invalid="true" switches the border to tone.danger.border and thickens it; disabled lowers opacity with control.disabled-opacity.'],
    propTokens: [
      { prop: 'aria-invalid="true"', property: 'border-color', token: 'tone.danger.border' },
      { prop: '(always)', property: 'min-block-size', token: 'control.height.medium' },
    ],
    composition: ['Always inside Field, which provides id, label, description and error wiring.'],
    states: ['Default, hover, focus-visible, invalid, read-only (sunken background) and disabled.'],
    accessibility: ['Placeholder is never a label.', 'The border meets 3:1 against the surface.'],
    responsive: ['Fills its container; Field controls the width.'],
    mistakes: ['Using placeholder instead of a label.'],
    tradeoffs: ['No size prop: every control shares control.height.medium so form rows align.'],
    sourcePaths: ['src/design-system/primitives/Input/Input.tsx', 'src/design-system/primitives/Input/Input.module.css'],
    Example: InputExample,
  },
  {
    id: 'select',
    purpose: 'Select styles the native select element and keeps the platform popup and keyboard behavior.',
    whenToUse: ['Choosing one option from a short list.'],
    whenNotToUse: ['Two or three options that should be visible at once: use radio buttons.'],
    props: [],
    nativeProps: 'Every select attribute passes through.',
    precedence: ['Invalid and disabled styling match Input.'],
    propTokens: [{ prop: '(always)', property: 'border-color', token: 'input.border' }],
    composition: ['Inside Field. The playground uses Select for every enumerated prop.'],
    states: ['Default, hover, focus-visible, invalid and disabled.'],
    accessibility: ['Native semantics: no ARIA needed.'],
    responsive: ['Fills its container.'],
    mistakes: ['Replacing it with a custom listbox without a strong reason.'],
    tradeoffs: ['The open popup cannot be themed; that is the price of native behavior on every platform.'],
    sourcePaths: ['src/design-system/primitives/Select/Select.tsx', 'src/design-system/primitives/Select/Select.module.css'],
    Example: SelectExample,
  },
  {
    id: 'checkbox',
    purpose: 'Checkbox pairs a native checkbox with its label and optional description.',
    whenToUse: ['Independent choices submitted with a form.', 'Filters in a group with a fieldset legend.'],
    whenNotToUse: ['Settings that apply immediately: use Switch.'],
    props: propsTable<CheckboxOwnProps>({
      label: { type: 'ReactNode', required: true, description: 'Visible label.' },
      description: { type: 'ReactNode', description: 'Hint linked with aria-describedby.' },
    }),
    nativeProps: 'Other input attributes (checked, defaultChecked, onChange, disabled, name) go to the input.',
    precedence: ['The input is native, so indeterminate can be set through a ref.'],
    propTokens: [{ prop: 'checked', property: 'accent-color', token: 'action.primary.background' }],
    composition: ['Group related checkboxes in a fieldset with a legend.'],
    states: ['Unchecked, checked, indeterminate, focus-visible and disabled.'],
    accessibility: ['Label click toggles the box.', 'Native forced-colors rendering.'],
    responsive: ['Label wraps beside the box.'],
    mistakes: ['A checkbox that saves immediately.'],
    tradeoffs: ['accent-color styles the native box with one token instead of a custom drawing.'],
    sourcePaths: ['src/design-system/primitives/Checkbox/Checkbox.tsx', 'src/design-system/primitives/Checkbox/Checkbox.module.css'],
    Example: CheckboxExample,
  },
  {
    id: 'switch',
    purpose: 'Switch is a native checkbox with role="switch" and a drawn track, for on/off settings that take effect immediately.',
    whenToUse: ['Preferences such as compact rows or reduced data.', 'Boolean props in the playground.'],
    whenNotToUse: ['Choices that are submitted later: use Checkbox.'],
    props: propsTable<SwitchOwnProps>({
      label: { type: 'ReactNode', required: true, description: 'Names the setting, not the state.' },
      description: { type: 'ReactNode', description: 'Hint linked with aria-describedby.' },
    }),
    nativeProps: 'Other input attributes go to the input; type and role are fixed.',
    precedence: ['checked state and focus ring are drawn on the track from the input’s :checked and :focus-visible.'],
    propTokens: [
      { prop: 'checked', property: 'background-color', token: 'switch.track-on' },
      { prop: 'unchecked', property: 'background-color', token: 'switch.track-off' },
    ],
    composition: ['Use inside forms or settings panels; it needs no Field because it labels itself.'],
    states: ['Off, on, focus-visible, disabled.'],
    accessibility: ['Space toggles; screen readers announce “switch, on/off”.', 'Forced-colors mode uses system colors for track and thumb.'],
    responsive: ['Track is a fixed size; the label wraps.'],
    mistakes: ['Label text “On” or “Enabled”, which duplicates the state.'],
    tradeoffs: ['The input is visually transparent over the track rather than hidden, so pointer, touch and assistive technology all hit the same element.'],
    sourcePaths: ['src/design-system/primitives/Switch/Switch.tsx', 'src/design-system/primitives/Switch/Switch.module.css'],
    Example: SwitchExample,
  },
  {
    id: 'progress',
    purpose: 'Progress shows determinate progress with a visible label associated with a native progress element.',
    whenToUse: ['Known amounts of completed work.'],
    whenNotToUse: ['Unknown durations: show a status message or Skeleton.'],
    props: propsTable<ProgressOwnProps>({
      label: { type: 'ReactNode', required: true, description: 'Visible label and accessible name.' },
      value: { type: 'number', required: true, description: 'Current value.' },
      max: { type: 'number', defaultValue: '100', description: 'Maximum value.' },
      valueText: { type: 'ReactNode', description: 'Visible summary. Defaults to a rounded percentage.' },
    }),
    nativeProps: 'className styles the wrapper; other props go to the progress element.',
    precedence: ['value is clamped between 0 and max for the percentage text.'],
    propTokens: [{ prop: 'value', property: 'bar color', token: 'action.primary.background' }],
    composition: ['Dashboards and long-running operations.'],
    states: ['Any value from 0 to max.'],
    accessibility: ['Native progress semantics with a label element.'],
    responsive: ['Fills its container.'],
    mistakes: ['Using progress for a spinner-like unknown wait.'],
    tradeoffs: ['Indeterminate mode is not offered; it rarely tells people more than a status message.'],
    sourcePaths: ['src/design-system/primitives/Progress/Progress.tsx', 'src/design-system/primitives/Progress/Progress.module.css'],
    Example: ProgressExample,
  },
  {
    id: 'skeleton',
    purpose: 'Skeleton draws placeholder shapes for content that is loading, sized from tokens and hidden from assistive technology.',
    whenToUse: ['Loading states of lists, cards and detail pages where the final layout is known.'],
    whenNotToUse: ['As the only loading signal: always pair with status text.'],
    props: propsTable<SkeletonOwnProps>({
      shape: { type: '"text" | "block" | "circle"', defaultValue: '"text"', description: 'Lines, a block or a circle.' },
      lines: { type: 'number', defaultValue: '3', description: 'Line count for text; the last line is shorter.' },
      size: { type: '"small" | "medium" | "large"', defaultValue: '"medium"', description: 'Block height or circle diameter from skeleton.size.*.' },
    }),
    nativeProps: 'Other div props pass through; aria-hidden is always set.',
    precedence: ['lines applies only to text; size applies only to block and circle. Irrelevant props are ignored, never errors.'],
    propTokens: [
      { prop: 'shape="block" size="large"', property: 'block-size', token: 'skeleton.size.large' },
      { prop: '(always)', property: 'background', token: 'skeleton.base' },
    ],
    composition: ['Inside a region with aria-busy="true" and a role="status" message.'],
    states: ['Animated shimmer; static under prefers-reduced-motion.'],
    accessibility: ['Always aria-hidden.', 'The shimmer stops for people who prefer reduced motion (base.css).'],
    responsive: ['Text and block shapes fill their container.'],
    mistakes: ['Skeletons that do not match the loaded layout, causing a jump.'],
    tradeoffs: ['Shimmer needs a highlight token in each theme.'],
    sourcePaths: ['src/design-system/primitives/Skeleton/Skeleton.tsx', 'src/design-system/primitives/Skeleton/Skeleton.module.css'],
    Example: SkeletonExample,
  },
  {
    id: 'visually-hidden',
    purpose: 'VisuallyHidden keeps text available to assistive technology without taking visual space.',
    whenToUse: ['Adding context to repeated controls, such as “Pin Button”.'],
    whenNotToUse: ['Hiding content from everyone: use the hidden attribute.'],
    props: [],
    nativeProps: 'All span props pass through.',
    precedence: [],
    propTokens: [],
    composition: ['Inside buttons and links.'],
    states: ['None.'],
    accessibility: ['Uses clip-path, not display: none, so it stays in the accessibility tree.'],
    responsive: ['None.'],
    mistakes: ['Hiding focusable elements with it.'],
    tradeoffs: ['Names built from visible and hidden text can contain extra spaces; tests match them with patterns.'],
    sourcePaths: ['src/design-system/primitives/VisuallyHidden/VisuallyHidden.tsx', 'src/design-system/primitives/VisuallyHidden/VisuallyHidden.module.css'],
    Example: VisuallyHiddenExample,
  },
];
